[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/payment/order"
  to = "/.netlify/functions/payment-order"
  status = 200
  force = true

[[redirects]]
  from = "/api/payment/verify"
  to = "/.netlify/functions/payment-verify"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
